### ISSUE TITLE
Still “experimental”?

### ISSUE THREAD

**Issue by stevengj** [Keno/StructIO.jl#22]
The repository still describes this package as experimental. Is that out of date?

**Comment by stevengj** [comment]
@Keno?

**Comment by Keno** [comment]
Well, there wasn't really any substantial improvement to this package since then and I don't think it's fully developed, but it's also almost a decade old at this point, so ... I'm fine with whatever description you would like.

**Comment by stevengj** [comment]
What major functionality is missing?  Or are there major bugs?

Is there any reason it would not be a good idea to depend on this package from a production package?

**Comment by Keno** [comment]
I haven't touched this package in a long time, but I don't believe it has any major issues. The biggest question is whether this the "right" way to solve this problem or the most efficient. But the package does what it does fine, as far as I know. ObjectFile.jl and friends use it afaik.

**Comment by stevengj** [comment]
Okay, I've edited the description to "binary I/O methods generated from Julia structure definitions" and removed the "experimental" language.
