### ISSUE TITLE
@io depends on StructIO being imported

### ISSUE THREAD

**Issue by maleadt** [Keno/StructIO.jl#24]
MWE:

```julia
julia> using StructIO: @io

julia> @io struct Foo
       end
ERROR: UndefVarError: `StructIO` not defined
```

The `@io` macro should probably resolve references to `StructIO` already.

**Comment by stevengj** [comment]
The problem is that it has to generate new functions like:
```jl
StructIO.packing_strategy(::MyType) = ...
```
I don't know of a way to do this if you don't at least have `import StructIO`?  Maybe the `@io` macro should just output an `import StructIO` statement?

**Comment by SimonDanisch** [comment]
Can it not do 
```julia
quote 
    $(StructIO).packing_strategy(::MyType) = ...
end
```

**Comment by stevengj** [comment]
Right, I've updated my PR to use this.
