### ISSUE TITLE
Failing pkg evaluator for 0.6 -- needs metadata update?

### ISSUE THREAD

**Issue by catawbasam** [Keno/StructIO.jl#6]
`struct` related error shows up in the 0.6 test log, but seems to be fixed on master.

**Comment by catawbasam** [comment]
Bump?   COFF.jl and DWARF.jl at minimum are affected.

**Comment by staticfloat** [comment]
+1

@Keno new release please.

**Comment by rapus95** [comment]
Is this still maintained? :/
Since for StrPack.jl it says "only semi-maintained" I'm curious what package i should use

**Comment by staticfloat** [comment]
@rapus95 I just submitted a rather large PR to fix things up for this package, I intend to continue using this package, and will maintain it if @Keno is too busy.

**Comment by Keno** [comment]
There've been tags since and I'm about to put out a tag for 0.7.
